export interface Player {
  id: string;
  name: string;
  shortName: string;
  country: string;
  countryId: string;
  flag: string;
  position: "GK" | "DEF" | "MID" | "FWD";
  era: "historic" | "current";
  number: number;
  birthYear: number;
  overall: number;
  pace: number;
  shooting: number;
  passing: number;
  dribbling: number;
  defending: number;
  physical: number;
  worldCupGoals: number;
  worldCupApps: number;
  worldCupTitles: number;
  emoji: string;
  trait: string;
}

export const players: Player[] = [
  // HISTÓRICOS
  {
    id: "pele",
    name: "Pelé",
    shortName: "PELÉ",
    country: "Brasil",
    countryId: "brazil",
    flag: "🇧🇷",
    position: "FWD",
    era: "historic",
    number: 10,
    birthYear: 1940,
    overall: 99,
    pace: 95,
    shooting: 99,
    passing: 92,
    dribbling: 99,
    defending: 45,
    physical: 88,
    worldCupGoals: 12,
    worldCupApps: 14,
    worldCupTitles: 3,
    emoji: "👑",
    trait: "El Rey",
  },
  {
    id: "maradona",
    name: "Diego Armando Maradona",
    shortName: "MARADONA",
    country: "Argentina",
    countryId: "argentina",
    flag: "🇦🇷",
    position: "FWD",
    era: "historic",
    number: 10,
    birthYear: 1960,
    overall: 99,
    pace: 92,
    shooting: 94,
    passing: 95,
    dribbling: 99,
    defending: 52,
    physical: 80,
    worldCupGoals: 8,
    worldCupApps: 21,
    worldCupTitles: 1,
    emoji: "🌪️",
    trait: "El Dios",
  },
  {
    id: "ronaldo_r9",
    name: "Ronaldo Nazário",
    shortName: "R9",
    country: "Brasil",
    countryId: "brazil",
    flag: "🇧🇷",
    position: "FWD",
    era: "historic",
    number: 9,
    birthYear: 1976,
    overall: 98,
    pace: 99,
    shooting: 98,
    passing: 85,
    dribbling: 97,
    defending: 30,
    physical: 90,
    worldCupGoals: 15,
    worldCupApps: 19,
    worldCupTitles: 2,
    emoji: "⚡",
    trait: "El Fenómeno",
  },
  {
    id: "zidane",
    name: "Zinedine Zidane",
    shortName: "ZIZOU",
    country: "Francia",
    countryId: "france",
    flag: "🇫🇷",
    position: "MID",
    era: "historic",
    number: 10,
    birthYear: 1972,
    overall: 98,
    pace: 78,
    shooting: 87,
    passing: 97,
    dribbling: 98,
    defending: 65,
    physical: 82,
    worldCupGoals: 5,
    worldCupApps: 12,
    worldCupTitles: 1,
    emoji: "🎭",
    trait: "El Maestro",
  },
  {
    id: "ronaldo_cr7_historic",
    name: "Ronaldo (CR7)",
    shortName: "CR7",
    country: "Portugal",
    countryId: "portugal",
    flag: "🇵🇹",
    position: "FWD",
    era: "historic",
    number: 7,
    birthYear: 1985,
    overall: 97,
    pace: 91,
    shooting: 97,
    passing: 82,
    dribbling: 95,
    defending: 35,
    physical: 93,
    worldCupGoals: 8,
    worldCupApps: 22,
    worldCupTitles: 0,
    emoji: "🦁",
    trait: "El Elegido",
  },
  {
    id: "messi_historic",
    name: "Lionel Messi",
    shortName: "LA PULGA",
    country: "Argentina",
    countryId: "argentina",
    flag: "🇦🇷",
    position: "FWD",
    era: "historic",
    number: 10,
    birthYear: 1987,
    overall: 99,
    pace: 88,
    shooting: 96,
    passing: 99,
    dribbling: 99,
    defending: 40,
    physical: 76,
    worldCupGoals: 13,
    worldCupApps: 26,
    worldCupTitles: 1,
    emoji: "🐐",
    trait: "El GOAT",
  },
  {
    id: "beckenbauer",
    name: "Franz Beckenbauer",
    shortName: "EL KAISER",
    country: "Alemania",
    countryId: "germany",
    flag: "🇩🇪",
    position: "DEF",
    era: "historic",
    number: 5,
    birthYear: 1945,
    overall: 97,
    pace: 72,
    shooting: 72,
    passing: 90,
    dribbling: 82,
    defending: 98,
    physical: 80,
    worldCupGoals: 4,
    worldCupApps: 18,
    worldCupTitles: 1,
    emoji: "🏰",
    trait: "El Kaiser",
  },
  {
    id: "cruyff",
    name: "Johan Cruyff",
    shortName: "CRUYFF",
    country: "Países Bajos",
    countryId: "netherlands",
    flag: "🇳🇱",
    position: "FWD",
    era: "historic",
    number: 14,
    birthYear: 1947,
    overall: 97,
    pace: 90,
    shooting: 88,
    passing: 95,
    dribbling: 97,
    defending: 60,
    physical: 75,
    worldCupGoals: 3,
    worldCupApps: 7,
    worldCupTitles: 0,
    emoji: "🌀",
    trait: "El Filósofo",
  },
  // ACTUALES
  {
    id: "mbappe",
    name: "Kylian Mbappé",
    shortName: "MBAPPÉ",
    country: "Francia",
    countryId: "france",
    flag: "🇫🇷",
    position: "FWD",
    era: "current",
    number: 10,
    birthYear: 1998,
    overall: 96,
    pace: 99,
    shooting: 94,
    passing: 82,
    dribbling: 95,
    defending: 38,
    physical: 82,
    worldCupGoals: 12,
    worldCupApps: 14,
    worldCupTitles: 1,
    emoji: "🚀",
    trait: "El Cohete",
  },
  {
    id: "vinicius",
    name: "Vinícius Júnior",
    shortName: "VINI JR",
    country: "Brasil",
    countryId: "brazil",
    flag: "🇧🇷",
    position: "FWD",
    era: "current",
    number: 7,
    birthYear: 2000,
    overall: 93,
    pace: 97,
    shooting: 88,
    passing: 81,
    dribbling: 97,
    defending: 32,
    physical: 75,
    worldCupGoals: 3,
    worldCupApps: 7,
    worldCupTitles: 0,
    emoji: "🎪",
    trait: "El Mago",
  },
  {
    id: "haaland",
    name: "Erling Haaland",
    shortName: "HAALAND",
    country: "Noruega",
    countryId: "norway",
    flag: "🇳🇴",
    position: "FWD",
    era: "current",
    number: 9,
    birthYear: 2000,
    overall: 95,
    pace: 89,
    shooting: 98,
    passing: 70,
    dribbling: 82,
    defending: 45,
    physical: 97,
    worldCupGoals: 0,
    worldCupApps: 0,
    worldCupTitles: 0,
    emoji: "🤖",
    trait: "La Máquina",
  },
  {
    id: "bellingham",
    name: "Jude Bellingham",
    shortName: "BELLINGHAM",
    country: "Inglaterra",
    countryId: "england",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    position: "MID",
    era: "current",
    number: 10,
    birthYear: 2003,
    overall: 93,
    pace: 85,
    shooting: 88,
    passing: 88,
    dribbling: 90,
    defending: 82,
    physical: 88,
    worldCupGoals: 3,
    worldCupApps: 7,
    worldCupTitles: 0,
    emoji: "⚔️",
    trait: "El Guerrero",
  },
  {
    id: "pedri",
    name: "Pedri",
    shortName: "PEDRI",
    country: "España",
    countryId: "spain",
    flag: "🇪🇸",
    position: "MID",
    era: "current",
    number: 8,
    birthYear: 2002,
    overall: 91,
    pace: 80,
    shooting: 79,
    passing: 93,
    dribbling: 93,
    defending: 75,
    physical: 72,
    worldCupGoals: 0,
    worldCupApps: 4,
    worldCupTitles: 0,
    emoji: "🎯",
    trait: "El Metronomo",
  },
  {
    id: "alisson",
    name: "Alisson Becker",
    shortName: "ALISSON",
    country: "Brasil",
    countryId: "brazil",
    flag: "🇧🇷",
    position: "GK",
    era: "current",
    number: 1,
    birthYear: 1992,
    overall: 92,
    pace: 50,
    shooting: 20,
    passing: 78,
    dribbling: 30,
    defending: 92,
    physical: 85,
    worldCupGoals: 0,
    worldCupApps: 7,
    worldCupTitles: 0,
    emoji: "🧤",
    trait: "El Muro",
  },
  {
    id: "modric",
    name: "Luka Modrić",
    shortName: "MODRIĆ",
    country: "Croacia",
    countryId: "croatia",
    flag: "🇭🇷",
    position: "MID",
    era: "current",
    number: 10,
    birthYear: 1985,
    overall: 93,
    pace: 78,
    shooting: 80,
    passing: 95,
    dribbling: 93,
    defending: 78,
    physical: 73,
    worldCupGoals: 2,
    worldCupApps: 17,
    worldCupTitles: 0,
    emoji: "🎻",
    trait: "El Virtuoso",
  },
];

export const managerComments: Record<string, Record<string, string[]>> = {
  mourinho: {
    pele: [
      "¿Pelé? Tres mundiales. Eso es trabajo. Los demás son turistas.",
      "Si yo hubiera entrenado a Pelé, habría ganado cinco Mundiales. Pero él no me necesitaba.",
    ],
    maradona: [
      "Maradona era impredecible. No se puede entrenar eso. Solo se puede observar y rezar.",
      "Con la mano de Dios o sin ella, ese gol al 86 es el más humano que vi en mi vida.",
    ],
    mbappe: [
      "Mbappé corre más rápido que mis estrategias. Y eso me molesta profundamente.",
      "Necesito un bus de dos pisos para pararlo. No lo digo como insulto.",
    ],
    messi_historic: [
      "He gastado más tiempo estudiando a Messi que a mis propios hijos. Y aún no lo entiendo.",
      "El hombre hace que el fútbol parezca injusto. Y yo soy el experto en injusticia.",
    ],
    haaland: [
      "Haaland no juega al fútbol, ejecuta algoritmos de gol. Inquietante.",
      "Le puse a mi analista a estudiar sus movimientos. El analista renunció.",
    ],
    default: [
      "Tácticamente interesante. Pero yo lo habría usado de otra manera.",
      "¿Mundiales ganados? Eso es lo único que importa en este deporte.",
    ],
  },
  klopp: {
    pele: [
      "¡PELÉ! ¡INCREÍBLE! ¡ESE HOMBRE INVENTÓ LA ALEGRÍA DEL FÚTBOL!",
      "Cuando ves los highlights de Pelé entiendes por qué esta profesión es un regalo.",
    ],
    maradona: [
      "Maradona era fútbol puro, sin filtros, sin excusas. Eso es lo más punk que existe.",
      "El tipo ganó un Mundial él solo. Eso no es fútbol, eso es arte de combate.",
    ],
    mbappe: [
      "¡Mbappé! ¡Gegenpressing con esteroides! ¡Me hace feliz solo verlo correr!",
      "Ese chico juega como si la cancha fuera demasiado pequeña para su talento.",
    ],
    messi_historic: [
      "Messi es el argumento definitivo de que Dios existe y le gusta el fútbol.",
      "¿Cómo explicás a Messi a alguien que no vio fútbol? No se puede. Solo se vive.",
    ],
    vinicius: [
      "¡Vini! ¡Intensidad pura! ¡Ese chico tiene música en las piernas!",
      "Vinícius es lo que pasa cuando el talento se encuentra con la alegría.",
    ],
    default: [
      "¡Increíble jugador! ¡El fútbol necesita más personas así!",
      "La energía de este tipo es contagiosa. ¡Eso me encanta!",
    ],
  },
  guardiola: {
    pele: [
      "La posición de Pelé dentro del sistema era perfecta incluso cuando no había sistema.",
      "Tres mundiales: cada uno con un equipo diferente. Eso es adaptabilidad táctica máxima.",
    ],
    maradona: [
      "Maradona rompía cualquier estructura táctica. Y eso, paradójicamente, era su estructura.",
      "El '86 fue un one-man-press. Un jugador presionando a once. Nunca lo volví a ver.",
    ],
    mbappe: [
      "La transición de Mbappé del pressing al contragolpe es... clínicamente perfecta.",
      "Sus números de cobertura de distancia son los mejores de la historia. Puro dato.",
    ],
    pedri: [
      "Pedri es la personificación del tiki-taka con alma. Cada pase tiene intención.",
      "Cuando Pedri juega, el equipo respira. Eso no se enseña, se tiene.",
    ],
    modric: [
      "Modrić gestiona el tiempo del partido como nadie. Tres segundos más, tres segundos menos. Matemática pura.",
      "Técnicamente es un reloj suizo. Nunca falla el timing.",
    ],
    default: [
      "Posicionalmente... hay cosas que mejorar. Tácticamente... hay mucho que hablar.",
      "El movimiento sin balón es lo que me interesa. Y aquí hay potencial.",
    ],
  },
  fergie: {
    pele: [
      "Pelé en el United... Dios mío. Habría ganado todo. Absolutamente todo.",
      "Tres Mundiales. Y lo hizo sin el privilegio de jugar en Old Trafford.",
    ],
    maradona: [
      "Maradona era un problema. Un hermoso, glorioso problema que ningún entrenador podía resolver.",
      "Si hubiera jugado para mí, lo habría protegido del mundo. Y del mundo de sí mismo.",
    ],
    ronaldo_cr7_historic: [
      "Le dije a Ronaldo que sería el mejor del mundo. Me miró como si ya lo supiera.",
      "El trabajo de Cristiano es el ejemplo que les pongo a todos mis jugadores. Sin excepción.",
    ],
    bellingham: [
      "Ese chico tiene lo que yo llamaba 'el gen del United'. Líder desde los veinte.",
      "Bellingham me recuerda a Robson, a Keane, a Scholes. El fútbol inglés está en buenas manos.",
    ],
    haaland: [
      "Haaland en el City... no me preguntes sobre eso. Que no me preguntes.",
      "Es una bestia. Un infierno para los defensas. Me alegra no tener que jugar contra él todos los años.",
    ],
    default: [
      "Buenas estadísticas. Pero ¿rinde bajo presión? Eso es lo único que importa.",
      "En mi época esto era diferente. Pero el talento sigue siendo talento.",
    ],
  },
};
