export interface Player {
  id: string;
  name: string;
  fullName: string;
  country: string;
  countryId: string;
  flagCode: string;
  position: "GK" | "DEF" | "MID" | "FWD";
  era: "historic" | "current";
  number: number;
  birthYear: number;
  overall: number;
  pace: number;
  shooting: number;
  passing: number;
  dribbling: number;
  defending: number;
  physical: number;
  wc_participaciones: number;
  wc_goles: number;
  wc_partidos: number;
  wc_titulos: string;
  imageUrl: string;
}

export const players: Player[] = [
  {
    id: "pele",
    name: "PELÉ",
    fullName: "Edson Arantes do Nascimento",
    country: "Brasil",
    countryId: "brazil",
    flagCode: "br",
    position: "FWD",
    era: "historic",
    number: 10,
    birthYear: 1940,
    overall: 99,
    pace: 95,
    shooting: 99,
    passing: 92,
    dribbling: 99,
    defending: 45,
    physical: 88,
    wc_participaciones: 4,
    wc_goles: 12,
    wc_partidos: 14,
    wc_titulos: "3x Campeón",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Pel%C3%A9_1970.jpg/440px-Pel%C3%A9_1970.jpg",
  },
  {
    id: "maradona",
    name: "MARADONA",
    fullName: "Diego Armando Maradona",
    country: "Argentina",
    countryId: "argentina",
    flagCode: "ar",
    position: "FWD",
    era: "historic",
    number: 10,
    birthYear: 1960,
    overall: 99,
    pace: 92,
    shooting: 94,
    passing: 95,
    dribbling: 99,
    defending: 52,
    physical: 80,
    wc_participaciones: 4,
    wc_goles: 8,
    wc_partidos: 21,
    wc_titulos: "1x Campeón",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Maradona-Mundial_86_con_la_copa.JPG/440px-Maradona-Mundial_86_con_la_copa.JPG",
  },
  {
    id: "ronaldo_r9",
    name: "RONALDO R9",
    fullName: "Ronaldo Luís Nazário de Lima",
    country: "Brasil",
    countryId: "brazil",
    flagCode: "br",
    position: "FWD",
    era: "historic",
    number: 9,
    birthYear: 1976,
    overall: 98,
    pace: 99,
    shooting: 98,
    passing: 85,
    dribbling: 97,
    defending: 30,
    physical: 90,
    wc_participaciones: 3,
    wc_goles: 15,
    wc_partidos: 19,
    wc_titulos: "2x Campeón",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Ronaldo_-_Foto_oficial_%281%29.jpg/440px-Ronaldo_-_Foto_oficial_%281%29.jpg",
  },
  {
    id: "zidane",
    name: "ZIDANE",
    fullName: "Zinedine Zidane",
    country: "Francia",
    countryId: "france",
    flagCode: "fr",
    position: "MID",
    era: "historic",
    number: 10,
    birthYear: 1972,
    overall: 98,
    pace: 78,
    shooting: 87,
    passing: 97,
    dribbling: 98,
    defending: 65,
    physical: 82,
    wc_participaciones: 3,
    wc_goles: 5,
    wc_partidos: 12,
    wc_titulos: "1x Campeón",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Zinedine_Zidane_2012.jpg/440px-Zinedine_Zidane_2012.jpg",
  },
  {
    id: "messi",
    name: "MESSI",
    fullName: "Lionel Andrés Messi",
    country: "Argentina",
    countryId: "argentina",
    flagCode: "ar",
    position: "FWD",
    era: "historic",
    number: 10,
    birthYear: 1987,
    overall: 99,
    pace: 88,
    shooting: 96,
    passing: 99,
    dribbling: 99,
    defending: 40,
    physical: 76,
    wc_participaciones: 5,
    wc_goles: 13,
    wc_partidos: 26,
    wc_titulos: "1x Campeón",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Messi_vs_Nigeria_2018.jpg/440px-Messi_vs_Nigeria_2018.jpg",
  },
  {
    id: "beckenbauer",
    name: "BECKENBAUER",
    fullName: "Franz Anton Beckenbauer",
    country: "Alemania",
    countryId: "germany",
    flagCode: "de",
    position: "DEF",
    era: "historic",
    number: 5,
    birthYear: 1945,
    overall: 97,
    pace: 72,
    shooting: 72,
    passing: 90,
    dribbling: 82,
    defending: 98,
    physical: 80,
    wc_participaciones: 4,
    wc_goles: 4,
    wc_partidos: 18,
    wc_titulos: "1x Campeón",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Franz_Beckenbauer.jpg/440px-Franz_Beckenbauer.jpg",
  },
  {
    id: "cruyff",
    name: "CRUYFF",
    fullName: "Hendrik Johannes Cruyff",
    country: "Países Bajos",
    countryId: "netherlands",
    flagCode: "nl",
    position: "FWD",
    era: "historic",
    number: 14,
    birthYear: 1947,
    overall: 97,
    pace: 90,
    shooting: 88,
    passing: 95,
    dribbling: 97,
    defending: 60,
    physical: 75,
    wc_participaciones: 1,
    wc_goles: 3,
    wc_partidos: 7,
    wc_titulos: "1x Subcampeón",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Johan_Cruyff_1974_%28cropped%29.jpg/440px-Johan_Cruyff_1974_%28cropped%29.jpg",
  },
  {
    id: "ronaldo_cr7",
    name: "C. RONALDO",
    fullName: "Cristiano Ronaldo dos Santos Aveiro",
    country: "Portugal",
    countryId: "portugal",
    flagCode: "pt",
    position: "FWD",
    era: "historic",
    number: 7,
    birthYear: 1985,
    overall: 97,
    pace: 91,
    shooting: 97,
    passing: 82,
    dribbling: 95,
    defending: 35,
    physical: 93,
    wc_participaciones: 5,
    wc_goles: 8,
    wc_partidos: 22,
    wc_titulos: "—",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cristiano_Ronaldo_2018.jpg/440px-Cristiano_Ronaldo_2018.jpg",
  },
  {
    id: "mbappe",
    name: "MBAPPÉ",
    fullName: "Kylian Mbappé Lottin",
    country: "Francia",
    countryId: "france",
    flagCode: "fr",
    position: "FWD",
    era: "current",
    number: 10,
    birthYear: 1998,
    overall: 96,
    pace: 99,
    shooting: 94,
    passing: 82,
    dribbling: 95,
    defending: 38,
    physical: 82,
    wc_participaciones: 2,
    wc_goles: 12,
    wc_partidos: 14,
    wc_titulos: "1x Campeón",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/2019-07-17_SG_Dynamo_Dresden_vs._Paris_Saint-Germain_F.C._by_Sandro_Halank–143_%28cropped%29.jpg/440px-2019-07-17_SG_Dynamo_Dresden_vs._Paris_Saint-Germain_F.C._by_Sandro_Halank–143_%28cropped%29.jpg",
  },
  {
    id: "vinicius",
    name: "VINÍCIUS JR.",
    fullName: "Vinícius José Paixão de Oliveira Júnior",
    country: "Brasil",
    countryId: "brazil",
    flagCode: "br",
    position: "FWD",
    era: "current",
    number: 7,
    birthYear: 2000,
    overall: 93,
    pace: 97,
    shooting: 88,
    passing: 81,
    dribbling: 97,
    defending: 32,
    physical: 75,
    wc_participaciones: 1,
    wc_goles: 3,
    wc_partidos: 7,
    wc_titulos: "—",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Vinicius_Junior_Brazil_2022_%28cropped%29.jpg/440px-Vinicius_Junior_Brazil_2022_%28cropped%29.jpg",
  },
  {
    id: "bellingham",
    name: "BELLINGHAM",
    fullName: "Jude Victor William Bellingham",
    country: "Inglaterra",
    countryId: "england",
    flagCode: "gb-eng",
    position: "MID",
    era: "current",
    number: 10,
    birthYear: 2003,
    overall: 93,
    pace: 85,
    shooting: 88,
    passing: 88,
    dribbling: 90,
    defending: 82,
    physical: 88,
    wc_participaciones: 1,
    wc_goles: 3,
    wc_partidos: 7,
    wc_titulos: "—",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Jude_Bellingham_England_2022.jpg/440px-Jude_Bellingham_England_2022.jpg",
  },
  {
    id: "modric",
    name: "MODRIĆ",
    fullName: "Luka Modrić",
    country: "Croacia",
    countryId: "croatia",
    flagCode: "hr",
    position: "MID",
    era: "current",
    number: 10,
    birthYear: 1985,
    overall: 93,
    pace: 78,
    shooting: 80,
    passing: 95,
    dribbling: 93,
    defending: 78,
    physical: 73,
    wc_participaciones: 4,
    wc_goles: 2,
    wc_partidos: 17,
    wc_titulos: "1x Subcampeón",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Luka_Modri%C4%87_2019.jpg/440px-Luka_Modri%C4%87_2019.jpg",
  },
  {
    id: "haaland",
    name: "HAALAND",
    fullName: "Erling Braut Haaland",
    country: "Noruega",
    countryId: "norway",
    flagCode: "no",
    position: "FWD",
    era: "current",
    number: 9,
    birthYear: 2000,
    overall: 95,
    pace: 89,
    shooting: 98,
    passing: 70,
    dribbling: 82,
    defending: 45,
    physical: 97,
    wc_participaciones: 0,
    wc_goles: 0,
    wc_partidos: 0,
    wc_titulos: "—",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Erling_Haaland_2023_%28cropped%29.jpg/440px-Erling_Haaland_2023_%28cropped%29.jpg",
  },
];

export const MANAGERS = [
  { id: "bilardo", name: "BILARDO", role: "DT Argentina 1982–1990" },
  { id: "ruggeri", name: "RUGGERI", role: "Campeón del Mundo 1986" },
  { id: "scaloni", name: "SCALONI", role: "DT Argentina 2018–presente" },
];

export const managerComments: Record<string, Record<string, string[]>> = {
  bilardo: {
    pele: [
      "Pelé era un jugador total. Técnica, físico, gol. No había forma de marcarlo con un solo hombre.",
      "Lo vi jugar en el 70. Imparable. Y eso que mis equipos se preparaban para todo.",
    ],
    maradona: [
      "Diego no necesitaba táctica. Era la táctica. Con él en la cancha, los once jugábamos para él.",
      "En el 86, Diego fue el mejor jugador de la historia. Lo digo yo, que lo dirigí.",
    ],
    messi: [
      "Lionel tiene algo que no se enseña. Con él en cancha, el equipo no necesita crear, él crea solo.",
      "En Qatar lo vi completo. Fue lo más parecido a Diego que vi en mucho tiempo.",
    ],
    ronaldo_r9: [
      "Ronaldo era peligroso porque en dos pasos te dejaba al arquero solo. Muy difícil de marcar.",
      "Físico, técnica y velocidad en el mismo jugador. Un problema serio para cualquier defensa.",
    ],
    mbappe: [
      "Mbappé tiene velocidad, desequilibrio y gol. Hay que cerrarlo antes de que arranque.",
      "A ese chico hay que taparlo desde el mediocampo. Si llega al área, ya está.",
    ],
    haaland: [
      "Haaland es un nueve de área. Potente, definidor. Hay que sacarlo del juego antes del último pase.",
      "Dentro del área es letal. No tiene la gambeta de los grandes, pero hay que respetarlo.",
    ],
    default: [
      "Hay que estudiarlo bien. Ningún jugador es invencible si lo analizás correctamente.",
      "El talento importa, pero sin trabajo táctico no alcanza para ganar un mundial.",
    ],
  },
  ruggeri: {
    pele: [
      "Pelé es la referencia. Tres mundiales ganados. No hay mucho más que decir.",
      "Lo estudié de grande. Era completo en todo. El más difícil de enmarcar en un solo concepto.",
    ],
    maradona: [
      "Jugué con Diego años. Te daba la pelota y ya sabías que algo iba a pasar.",
      "En el 86 fue el mejor jugador de la historia en un mundial. Punto. No hay discusión.",
    ],
    messi: [
      "Leo es diferente a todos. Lo ves correr y parece que no hace nada, y de repente está en el área.",
      "Qatar fue hermoso. Ver a Leo levantar la Copa fue lo más lindo que vi desde el 86.",
    ],
    beckenbauer: [
      "Beckenbauer era un defensor que jugaba al fútbol de verdad. Muy difícil de marcar.",
      "Construía el juego desde atrás como nadie. En mi época eso era rarísimo.",
    ],
    haaland: [
      "Un nueve así te rompe la línea si te descuidás un segundo. Hay que estar muy atento.",
      "Potente, rápido para ser tan grande. Hoy sería muy difícil marcarlo mano a mano.",
    ],
    mbappe: [
      "Ese chico corre como el demonio. Imaginate tener que salir a marcarlo en una final de mundial.",
      "La velocidad que tiene es un problema serio para cualquier defensa del mundo.",
    ],
    cruyff: [
      "Cruyff te sacaba con un movimiento. Te miraba para un lado y salía para el otro.",
      "Técnico y veloz. El tipo de jugador que te hace quedar mal aunque estés bien parado.",
    ],
    default: [
      "Lo importante es el trabajo. El talento sin sacrificio no llega lejos en los mundiales.",
      "Hay jugadores que se ven bien pero en los partidos difíciles desaparecen. Ese es el filtro real.",
    ],
  },
  scaloni: {
    pele: [
      "Pelé es la referencia histórica máxima. Tres mundiales hablan solos.",
      "Cuando hablo de legado con el grupo, siempre aparece su nombre.",
    ],
    maradona: [
      "Diego es nuestra historia. Lo que hizo en el 86 no se puede explicar, solo se siente.",
      "Cada vez que entro a la cancha con Argentina, pienso en lo que él construyó.",
    ],
    messi: [
      "Con Leo trabajé años. Lo que más me sorprende es su capacidad de leer el juego antes que nadie.",
      "Qatar fue la culminación de todo. El mejor jugador de la historia coronado campeón del mundo.",
    ],
    mbappe: [
      "Kylian es un jugador diferencial. En la final del 22 lo sufrimos. Puede cambiar un partido solo.",
      "Tiene todo para ser el mejor de su generación. Velocidad, técnica, gol. Hay que prepararse bien.",
    ],
    bellingham: [
      "Bellingham me parece un centrocampista completo. Joven pero con temperamento de líder.",
      "Es el tipo de jugador que marca diferencia en los partidos clave. Lo seguí mucho.",
    ],
    modric: [
      "Modrić es un ejemplo de madurez futbolística. Lo enfrenté como DT y siempre me complicó.",
      "Tiene una lectura del juego que pocos tienen. Todavía rindiendo al máximo nivel es notable.",
    ],
    vinicius: [
      "Vinícius es un jugador difícil de controlar en transición. Muy rápido y con buen uno contra uno.",
      "Brasil lo tiene bien posicionado para el próximo mundial. Hay que prepararse para enfrentarlo.",
    ],
    default: [
      "Es un jugador que hay que analizar en profundidad antes de enfrentarlo.",
      "El fútbol de alto nivel requiere preparación. Cada jugador tiene algo que explotar.",
    ],
  },
};

export function getVestuarioComments(playerId: string): Array<{ managerId: string; comment: string }> {
  return MANAGERS.map((manager, idx) => {
    const commentSet = managerComments[manager.id];
    const pool = commentSet?.[playerId] ?? commentSet?.["default"] ?? ["Sin comentarios."];
    return {
      managerId: manager.id,
      comment: pool[idx % pool.length] ?? pool[0],
    };
  });
}
