/**
 * Team name -> ISO 3166-1 alpha-2 country code for flagcdn.com
 * Used for national teams and club countries
 */
export const teamToCountryCode: Record<string, string> = {
  // National teams
  "Argentina": "ar",
  "Brazil": "br",
  "Portugal": "pt",
  "Spain": "es",
  "France": "fr",
  "Germany": "de",
  "Italy": "it",
  "England": "gb",
  "Netherlands": "nl",
  "Uruguay": "uy",
  "Belgium": "be",
  "Croatia": "hr",
  "Mexico": "mx",
  "USA": "us",
  "United States": "us",
  "Canada": "ca",
  "Colombia": "co",
  "Switzerland": "ch",
  "Japan": "jp",
  "South Korea": "kr",
  "Morocco": "ma",
  "Australia": "au",
  "Qatar": "qa",
  "Saudi Arabia": "sa",
  "Egypt": "eg",
  "Iran": "ir",
  "Ghana": "gh",
  "Senegal": "sn",
  "Tunisia": "tn",
  "Ecuador": "ec",
  "Paraguay": "py",
  "Ivory Coast": "ci",
  "Côte d'Ivoire": "ci",
  "Austria": "at",
  "Algeria": "dz",
  "Jordan": "jo",
  "Norway": "no",
  "Scotland": "gb-sct",
  "Haiti": "ht",
  "Panama": "pa",
  "South Africa": "za",
  "Cabo Verde": "cv",
  "Cape Verde": "cv",
  "New Zealand": "nz",
  "Curaçao": "cw",
  "Uzbekistan": "uz",
  // Clubs (by country)
  "Barcelona": "es",
  "Real Madrid": "es",
  "Inter Milan": "it",
  "AC Milan": "it",
  "Manchester City": "gb",
  "Liverpool": "gb",
  "Bayern Munich": "de",
  "Borussia Dortmund": "de",
  "Marseille": "fr",
  "PSG": "fr",
  "Paris Saint-Germain": "fr",
  "River Plate": "ar",
  "Boca Juniors": "ar",
};

export function getCountryCode(teamName: string): string | undefined {
  return teamToCountryCode[teamName];
}