export interface TeamStats {
  id: string;
  name: string;
  flagCode: string; // for flagcdn.com
  confederation: string;
  participations: number; // including 2026
  bestPosition: string;
  played: number;
  won: number;
  drawn: number;
  lost: number;
  goalsFor: number;
  goalsAgainst: number;
  titles: number;
  finals: number;
  semifinals: number;
  firstYear: number;
  lastYear: number; // 2026
  topRival: string; // team they've faced most in WC history
}

export interface H2HRecord {
  opponent: string;
  played: number;
  won: number;
  drawn: number;
  lost: number;
  goalsFor: number;
  goalsAgainst: number;
}

export interface TeamH2H {
  teamId: string;
  records: H2HRecord[];
}

export const worldCupTeams: TeamStats[] = [
  // ── CONMEBOL ─────────────────────────────────────────────────────────────
  {
    id: "brazil",
    name: "Brasil",
    flagCode: "br",
    confederation: "CONMEBOL",
    participations: 23,
    bestPosition: "Campeón (1958, 1962, 1970, 1994, 2002)",
    played: 114,
    won: 76,
    drawn: 19,
    lost: 19,
    goalsFor: 237,
    goalsAgainst: 101,
    titles: 5,
    finals: 7,
    semifinals: 11,
    firstYear: 1930,
    lastYear: 2026,
    topRival: "Suecia",
  },
  {
    id: "argentina",
    name: "Argentina",
    flagCode: "ar",
    confederation: "CONMEBOL",
    participations: 19,
    bestPosition: "Campeón (1978, 1986, 2022)",
    played: 88,
    won: 47,
    drawn: 16,
    lost: 25,
    goalsFor: 145,
    goalsAgainst: 97,
    titles: 3,
    finals: 5,
    semifinals: 6,
    firstYear: 1930,
    lastYear: 2026,
    topRival: "Alemania",
  },
  {
    id: "uruguay",
    name: "Uruguay",
    flagCode: "uy",
    confederation: "CONMEBOL",
    participations: 15,
    bestPosition: "Campeón (1930, 1950)",
    played: 56,
    won: 27,
    drawn: 10,
    lost: 19,
    goalsFor: 87,
    goalsAgainst: 74,
    titles: 2,
    finals: 2,
    semifinals: 5,
    firstYear: 1930,
    lastYear: 2026,
    topRival: "Bolivia",
  },
  {
    id: "colombia",
    name: "Colombia",
    flagCode: "co",
    confederation: "CONMEBOL",
    participations: 7,
    bestPosition: "Cuartos de final (2014)",
    played: 28,
    won: 12,
    drawn: 6,
    lost: 10,
    goalsFor: 41,
    goalsAgainst: 37,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1962,
    lastYear: 2026,
    topRival: "Costa Rica",
  },
  {
    id: "ecuador",
    name: "Ecuador",
    flagCode: "ec",
    confederation: "CONMEBOL",
    participations: 5,
    bestPosition: "Octavos de final (2006)",
    played: 15,
    won: 4,
    drawn: 3,
    lost: 8,
    goalsFor: 15,
    goalsAgainst: 23,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 2002,
    lastYear: 2026,
    topRival: "Polonia",
  },
  {
    id: "paraguay",
    name: "Paraguay",
    flagCode: "py",
    confederation: "CONMEBOL",
    participations: 9,
    bestPosition: "Cuartos de final (1954, 2010)",
    played: 28,
    won: 9,
    drawn: 8,
    lost: 11,
    goalsFor: 35,
    goalsAgainst: 42,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1930,
    lastYear: 2026,
    topRival: "Yugoslavia",
  },

  // ── UEFA ─────────────────────────────────────────────────────────────────
  {
    id: "germany",
    name: "Alemania",
    flagCode: "de",
    confederation: "UEFA",
    participations: 21,
    bestPosition: "Campeón (1954, 1974, 1990, 2014)",
    played: 109,
    won: 67,
    drawn: 20,
    lost: 22,
    goalsFor: 226,
    goalsAgainst: 125,
    titles: 4,
    finals: 8,
    semifinals: 13,
    firstYear: 1934,
    lastYear: 2026,
    topRival: "Yugoslavia",
  },
  {
    id: "france",
    name: "Francia",
    flagCode: "fr",
    confederation: "UEFA",
    participations: 17,
    bestPosition: "Campeón (1998, 2018)",
    played: 66,
    won: 38,
    drawn: 13,
    lost: 15,
    goalsFor: 120,
    goalsAgainst: 71,
    titles: 2,
    finals: 3,
    semifinals: 6,
    firstYear: 1930,
    lastYear: 2026,
    topRival: "México",
  },
  {
    id: "spain",
    name: "España",
    flagCode: "es",
    confederation: "UEFA",
    participations: 17,
    bestPosition: "Campeón (2010)",
    played: 67,
    won: 33,
    drawn: 15,
    lost: 19,
    goalsFor: 99,
    goalsAgainst: 77,
    titles: 1,
    finals: 1,
    semifinals: 2,
    firstYear: 1934,
    lastYear: 2026,
    topRival: "Yugoslavia",
  },
  {
    id: "england",
    name: "Inglaterra",
    flagCode: "gb-eng",
    confederation: "UEFA",
    participations: 17,
    bestPosition: "Campeón (1966)",
    played: 69,
    won: 32,
    drawn: 21,
    lost: 16,
    goalsFor: 91,
    goalsAgainst: 64,
    titles: 1,
    finals: 1,
    semifinals: 3,
    firstYear: 1950,
    lastYear: 2026,
    topRival: "Argentina",
  },
  {
    id: "netherlands",
    name: "Países Bajos",
    flagCode: "nl",
    confederation: "UEFA",
    participations: 12,
    bestPosition: "Subcampeón (1974, 1978, 2010)",
    played: 52,
    won: 28,
    drawn: 10,
    lost: 14,
    goalsFor: 90,
    goalsAgainst: 60,
    titles: 0,
    finals: 3,
    semifinals: 4,
    firstYear: 1934,
    lastYear: 2026,
    topRival: "Bélgica",
  },
  {
    id: "portugal",
    name: "Portugal",
    flagCode: "pt",
    confederation: "UEFA",
    participations: 9,
    bestPosition: "Tercer puesto (1966)",
    played: 37,
    won: 20,
    drawn: 7,
    lost: 10,
    goalsFor: 71,
    goalsAgainst: 43,
    titles: 0,
    finals: 0,
    semifinals: 2,
    firstYear: 1966,
    lastYear: 2026,
    topRival: "España",
  },
  {
    id: "croatia",
    name: "Croacia",
    flagCode: "hr",
    confederation: "UEFA",
    participations: 7,
    bestPosition: "Subcampeón (2018)",
    played: 26,
    won: 14,
    drawn: 4,
    lost: 8,
    goalsFor: 47,
    goalsAgainst: 32,
    titles: 0,
    finals: 1,
    semifinals: 2,
    firstYear: 1998,
    lastYear: 2026,
    topRival: "Francia",
  },
  {
    id: "belgium",
    name: "Bélgica",
    flagCode: "be",
    confederation: "UEFA",
    participations: 15,
    bestPosition: "Tercer puesto (2018)",
    played: 45,
    won: 21,
    drawn: 9,
    lost: 15,
    goalsFor: 67,
    goalsAgainst: 53,
    titles: 0,
    finals: 0,
    semifinals: 2,
    firstYear: 1930,
    lastYear: 2026,
    topRival: "Paraguay",
  },
  {
    id: "switzerland",
    name: "Suiza",
    flagCode: "ch",
    confederation: "UEFA",
    participations: 13,
    bestPosition: "Cuartos de final (1934, 1938, 1954)",
    played: 40,
    won: 15,
    drawn: 8,
    lost: 17,
    goalsFor: 62,
    goalsAgainst: 73,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1934,
    lastYear: 2026,
    topRival: "Alemania",
  },
  {
    id: "austria",
    name: "Austria",
    flagCode: "at",
    confederation: "UEFA",
    participations: 8,
    bestPosition: "Tercer puesto (1954)",
    played: 29,
    won: 12,
    drawn: 4,
    lost: 13,
    goalsFor: 43,
    goalsAgainst: 47,
    titles: 0,
    finals: 0,
    semifinals: 2,
    firstYear: 1934,
    lastYear: 2026,
    topRival: "Alemania",
  },
  {
    id: "scotland",
    name: "Escocia",
    flagCode: "gb-sct",
    confederation: "UEFA",
    participations: 9,
    bestPosition: "Fase de grupos",
    played: 23,
    won: 4,
    drawn: 7,
    lost: 12,
    goalsFor: 25,
    goalsAgainst: 41,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1954,
    lastYear: 2026,
    topRival: "Brasil",
  },
  {
    id: "norway",
    name: "Noruega",
    flagCode: "no",
    confederation: "UEFA",
    participations: 4,
    bestPosition: "Octavos de final",
    played: 8,
    won: 2,
    drawn: 3,
    lost: 3,
    goalsFor: 7,
    goalsAgainst: 8,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1938,
    lastYear: 2026,
    topRival: "Brasil",
  },

  // ── CONCACAF ──────────────────────────────────────────────────────────────
  {
    id: "usa",
    name: "Estados Unidos",
    flagCode: "us",
    confederation: "CONCACAF",
    participations: 12,
    bestPosition: "Tercer puesto (1930)",
    played: 36,
    won: 12,
    drawn: 8,
    lost: 16,
    goalsFor: 43,
    goalsAgainst: 61,
    titles: 0,
    finals: 0,
    semifinals: 1,
    firstYear: 1930,
    lastYear: 2026,
    topRival: "Italia",
  },
  {
    id: "mexico",
    name: "México",
    flagCode: "mx",
    confederation: "CONCACAF",
    participations: 18,
    bestPosition: "Cuartos de final (1970, 1986)",
    played: 57,
    won: 16,
    drawn: 14,
    lost: 27,
    goalsFor: 60,
    goalsAgainst: 99,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1930,
    lastYear: 2026,
    topRival: "Bulgaria",
  },
  {
    id: "canada",
    name: "Canadá",
    flagCode: "ca",
    confederation: "CONCACAF",
    participations: 3,
    bestPosition: "Cuartos de final (2022)",
    played: 7,
    won: 1,
    drawn: 1,
    lost: 5,
    goalsFor: 5,
    goalsAgainst: 15,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1986,
    lastYear: 2026,
    topRival: "Francia",
  },
  {
    id: "panama",
    name: "Panamá",
    flagCode: "pa",
    confederation: "CONCACAF",
    participations: 2,
    bestPosition: "Fase de grupos",
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    goalsFor: 2,
    goalsAgainst: 11,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 2018,
    lastYear: 2026,
    topRival: "Bélgica",
  },
  {
    id: "curacao",
    name: "Curazao",
    flagCode: "cw",
    confederation: "CONCACAF",
    participations: 1,
    bestPosition: "Primera participación",
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 2026,
    lastYear: 2026,
    topRival: "—",
  },
  {
    id: "haiti",
    name: "Haití",
    flagCode: "ht",
    confederation: "CONCACAF",
    participations: 2,
    bestPosition: "Fase de grupos (1974)",
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    goalsFor: 2,
    goalsAgainst: 14,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1974,
    lastYear: 2026,
    topRival: "Argentina",
  },

  // ── CAF ───────────────────────────────────────────────────────────────────
  {
    id: "morocco",
    name: "Marruecos",
    flagCode: "ma",
    confederation: "CAF",
    participations: 7,
    bestPosition: "Cuarto puesto (2022)",
    played: 22,
    won: 8,
    drawn: 4,
    lost: 10,
    goalsFor: 24,
    goalsAgainst: 29,
    titles: 0,
    finals: 0,
    semifinals: 1,
    firstYear: 1970,
    lastYear: 2026,
    topRival: "España",
  },
  {
    id: "senegal",
    name: "Senegal",
    flagCode: "sn",
    confederation: "CAF",
    participations: 4,
    bestPosition: "Cuartos de final (2002)",
    played: 13,
    won: 5,
    drawn: 2,
    lost: 6,
    goalsFor: 14,
    goalsAgainst: 16,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 2002,
    lastYear: 2026,
    topRival: "Colombia",
  },
  {
    id: "south_africa",
    name: "Sudáfrica",
    flagCode: "za",
    confederation: "CAF",
    participations: 4,
    bestPosition: "Fase de grupos",
    played: 12,
    won: 2,
    drawn: 3,
    lost: 7,
    goalsFor: 11,
    goalsAgainst: 21,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1998,
    lastYear: 2026,
    topRival: "Arabia Saudita",
  },
  {
    id: "ghana",
    name: "Ghana",
    flagCode: "gh",
    confederation: "CAF",
    participations: 5,
    bestPosition: "Cuartos de final (2010)",
    played: 16,
    won: 5,
    drawn: 3,
    lost: 8,
    goalsFor: 18,
    goalsAgainst: 25,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 2006,
    lastYear: 2026,
    topRival: "Alemania",
  },
  {
    id: "ivory_coast",
    name: "Costa de Marfil",
    flagCode: "ci",
    confederation: "CAF",
    participations: 4,
    bestPosition: "Fase de grupos",
    played: 12,
    won: 4,
    drawn: 1,
    lost: 7,
    goalsFor: 13,
    goalsAgainst: 20,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 2006,
    lastYear: 2026,
    topRival: "Colombia",
  },
  {
    id: "tunisia",
    name: "Túnez",
    flagCode: "tn",
    confederation: "CAF",
    participations: 7,
    bestPosition: "Fase de grupos",
    played: 18,
    won: 3,
    drawn: 4,
    lost: 11,
    goalsFor: 12,
    goalsAgainst: 29,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1978,
    lastYear: 2026,
    topRival: "México",
  },
  {
    id: "algeria",
    name: "Argelia",
    flagCode: "dz",
    confederation: "CAF",
    participations: 5,
    bestPosition: "Octavos de final (2014)",
    played: 14,
    won: 4,
    drawn: 1,
    lost: 9,
    goalsFor: 16,
    goalsAgainst: 30,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1982,
    lastYear: 2026,
    topRival: "Alemania",
  },
  {
    id: "egypt",
    name: "Egipto",
    flagCode: "eg",
    confederation: "CAF",
    participations: 4,
    bestPosition: "Octavos de final (1934)",
    played: 10,
    won: 2,
    drawn: 2,
    lost: 6,
    goalsFor: 10,
    goalsAgainst: 21,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1934,
    lastYear: 2026,
    topRival: "Alemania",
  },
  {
    id: "cape_verde",
    name: "Cabo Verde",
    flagCode: "cv",
    confederation: "CAF",
    participations: 1,
    bestPosition: "Primera participación",
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 2026,
    lastYear: 2026,
    topRival: "—",
  },

  // ── AFC ───────────────────────────────────────────────────────────────────
  {
    id: "japan",
    name: "Japón",
    flagCode: "jp",
    confederation: "AFC",
    participations: 8,
    bestPosition: "Cuartos de final (2002, 2022)",
    played: 24,
    won: 9,
    drawn: 4,
    lost: 11,
    goalsFor: 28,
    goalsAgainst: 37,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1998,
    lastYear: 2026,
    topRival: "Bélgica",
  },
  {
    id: "south_korea",
    name: "Corea del Sur",
    flagCode: "kr",
    confederation: "AFC",
    participations: 12,
    bestPosition: "Semifinal (2002)",
    played: 38,
    won: 10,
    drawn: 10,
    lost: 18,
    goalsFor: 43,
    goalsAgainst: 67,
    titles: 0,
    finals: 0,
    semifinals: 1,
    firstYear: 1954,
    lastYear: 2026,
    topRival: "Bolivia",
  },
  {
    id: "iran",
    name: "Irán",
    flagCode: "ir",
    confederation: "AFC",
    participations: 7,
    bestPosition: "Fase de grupos",
    played: 18,
    won: 3,
    drawn: 3,
    lost: 12,
    goalsFor: 18,
    goalsAgainst: 37,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1978,
    lastYear: 2026,
    topRival: "Marruecos",
  },
  {
    id: "australia",
    name: "Australia",
    flagCode: "au",
    confederation: "AFC",
    participations: 7,
    bestPosition: "Octavos de final (2006, 2022)",
    played: 19,
    won: 5,
    drawn: 3,
    lost: 11,
    goalsFor: 21,
    goalsAgainst: 41,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1974,
    lastYear: 2026,
    topRival: "Alemania",
  },
  {
    id: "saudi_arabia",
    name: "Arabia Saudita",
    flagCode: "sa",
    confederation: "AFC",
    participations: 7,
    bestPosition: "Octavos de final (1994)",
    played: 18,
    won: 4,
    drawn: 2,
    lost: 12,
    goalsFor: 20,
    goalsAgainst: 40,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1994,
    lastYear: 2026,
    topRival: "Francia",
  },
  {
    id: "qatar",
    name: "Qatar",
    flagCode: "qa",
    confederation: "AFC",
    participations: 2,
    bestPosition: "Fase de grupos (2022)",
    played: 3,
    won: 0,
    drawn: 0,
    lost: 3,
    goalsFor: 1,
    goalsAgainst: 7,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 2022,
    lastYear: 2026,
    topRival: "Ecuador",
  },
  {
    id: "jordan",
    name: "Jordania",
    flagCode: "jo",
    confederation: "AFC",
    participations: 1,
    bestPosition: "Primera participación",
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 2026,
    lastYear: 2026,
    topRival: "—",
  },
  {
    id: "uzbekistan",
    name: "Uzbekistán",
    flagCode: "uz",
    confederation: "AFC",
    participations: 1,
    bestPosition: "Primera participación",
    played: 0,
    won: 0,
    drawn: 0,
    lost: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 2026,
    lastYear: 2026,
    topRival: "—",
  },

  // ── OFC ───────────────────────────────────────────────────────────────────
  {
    id: "new_zealand",
    name: "Nueva Zelanda",
    flagCode: "nz",
    confederation: "OFC",
    participations: 3,
    bestPosition: "Fase de grupos",
    played: 6,
    won: 1,
    drawn: 0,
    lost: 5,
    goalsFor: 4,
    goalsAgainst: 16,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1982,
    lastYear: 2026,
    topRival: "Italia",
  },
];

export const h2hData: TeamH2H[] = [
  {
    teamId: "brazil",
    records: [
      { opponent: "Suecia", played: 11, won: 7, drawn: 2, lost: 2, goalsFor: 21, goalsAgainst: 11 },
      { opponent: "Argentina", played: 9, won: 4, drawn: 2, lost: 3, goalsFor: 14, goalsAgainst: 12 },
      { opponent: "Alemania", played: 8, won: 3, drawn: 1, lost: 4, goalsFor: 14, goalsAgainst: 18 },
      { opponent: "Italia", played: 4, won: 2, drawn: 1, lost: 1, goalsFor: 6, goalsAgainst: 5 },
      { opponent: "Francia", played: 4, won: 2, drawn: 0, lost: 2, goalsFor: 4, goalsAgainst: 5 },
    ],
  },
  {
    teamId: "argentina",
    records: [
      { opponent: "Alemania", played: 7, won: 2, drawn: 2, lost: 3, goalsFor: 10, goalsAgainst: 12 },
      { opponent: "Brasil", played: 9, won: 3, drawn: 2, lost: 4, goalsFor: 12, goalsAgainst: 14 },
      { opponent: "Países Bajos", played: 6, won: 3, drawn: 2, lost: 1, goalsFor: 8, goalsAgainst: 6 },
      { opponent: "Francia", played: 3, won: 2, drawn: 0, lost: 1, goalsFor: 8, goalsAgainst: 7 },
      { opponent: "Italia", played: 2, won: 1, drawn: 0, lost: 1, goalsFor: 2, goalsAgainst: 2 },
    ],
  },
  {
    teamId: "germany",
    records: [
      { opponent: "Yugoslavia", played: 9, won: 6, drawn: 1, lost: 2, goalsFor: 20, goalsAgainst: 10 },
      { opponent: "Brasil", played: 8, won: 4, drawn: 1, lost: 3, goalsFor: 18, goalsAgainst: 14 },
      { opponent: "Argentina", played: 7, won: 3, drawn: 2, lost: 2, goalsFor: 12, goalsAgainst: 10 },
      { opponent: "Francia", played: 7, won: 4, drawn: 1, lost: 2, goalsFor: 15, goalsAgainst: 9 },
      { opponent: "Suecia", played: 6, won: 5, drawn: 0, lost: 1, goalsFor: 17, goalsAgainst: 7 },
    ],
  },
  {
    teamId: "france",
    records: [
      { opponent: "México", played: 4, won: 3, drawn: 1, lost: 0, goalsFor: 8, goalsAgainst: 2 },
      { opponent: "Alemania", played: 7, won: 2, drawn: 1, lost: 4, goalsFor: 9, goalsAgainst: 15 },
      { opponent: "Brasil", played: 4, won: 2, drawn: 0, lost: 2, goalsFor: 5, goalsAgainst: 4 },
      { opponent: "Argentina", played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 7, goalsAgainst: 8 },
      { opponent: "Italia", played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 4, goalsAgainst: 5 },
    ],
  },
  {
    teamId: "england",
    records: [
      { opponent: "Argentina", played: 5, won: 2, drawn: 1, lost: 2, goalsFor: 7, goalsAgainst: 7 },
      { opponent: "Alemania", played: 5, won: 1, drawn: 0, lost: 4, goalsFor: 5, goalsAgainst: 12 },
      { opponent: "Brasil", played: 5, won: 1, drawn: 0, lost: 4, goalsFor: 3, goalsAgainst: 8 },
      { opponent: "Colombia", played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 4, goalsAgainst: 4 },
      { opponent: "Paraguay", played: 2, won: 2, drawn: 0, lost: 0, goalsFor: 5, goalsAgainst: 1 },
    ],
  },
  {
    teamId: "spain",
    records: [
      { opponent: "Yugoslavia", played: 5, won: 1, drawn: 1, lost: 3, goalsFor: 7, goalsAgainst: 11 },
      { opponent: "Brasil", played: 4, won: 0, drawn: 2, lost: 2, goalsFor: 3, goalsAgainst: 6 },
      { opponent: "Portugal", played: 3, won: 2, drawn: 0, lost: 1, goalsFor: 5, goalsAgainst: 3 },
      { opponent: "Francia", played: 3, won: 1, drawn: 2, lost: 0, goalsFor: 4, goalsAgainst: 2 },
      { opponent: "Marruecos", played: 2, won: 0, drawn: 2, lost: 0, goalsFor: 1, goalsAgainst: 1 },
    ],
  },
  {
    teamId: "morocco",
    records: [
      { opponent: "España", played: 2, won: 0, drawn: 2, lost: 0, goalsFor: 1, goalsAgainst: 1 },
      { opponent: "Portugal", played: 2, won: 1, drawn: 0, lost: 1, goalsFor: 2, goalsAgainst: 1 },
      { opponent: "Francia", played: 2, won: 0, drawn: 0, lost: 2, goalsFor: 0, goalsAgainst: 3 },
      { opponent: "Alemania", played: 1, won: 0, drawn: 0, lost: 1, goalsFor: 1, goalsAgainst: 2 },
      { opponent: "Bélgica", played: 1, won: 1, drawn: 0, lost: 0, goalsFor: 2, goalsAgainst: 0 },
    ],
  },
  {
    teamId: "mexico",
    records: [
      { opponent: "Bulgaria", played: 5, won: 3, drawn: 1, lost: 1, goalsFor: 9, goalsAgainst: 4 },
      { opponent: "Brasil", played: 4, won: 0, drawn: 1, lost: 3, goalsFor: 1, goalsAgainst: 6 },
      { opponent: "Alemania", played: 3, won: 0, drawn: 1, lost: 2, goalsFor: 2, goalsAgainst: 5 },
      { opponent: "Argentina", played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 2, goalsAgainst: 7 },
      { opponent: "Francia", played: 4, won: 0, drawn: 1, lost: 3, goalsFor: 2, goalsAgainst: 8 },
    ],
  },
  {
    teamId: "japan",
    records: [
      { opponent: "Bélgica", played: 3, won: 0, drawn: 1, lost: 2, goalsFor: 4, goalsAgainst: 8 },
      { opponent: "Colombia", played: 2, won: 1, drawn: 0, lost: 1, goalsFor: 3, goalsAgainst: 3 },
      { opponent: "Croacia", played: 2, won: 0, drawn: 1, lost: 1, goalsFor: 2, goalsAgainst: 2 },
      { opponent: "Polonia", played: 2, won: 1, drawn: 0, lost: 1, goalsFor: 3, goalsAgainst: 3 },
      { opponent: "Alemania", played: 2, won: 1, drawn: 0, lost: 1, goalsFor: 3, goalsAgainst: 5 },
    ],
  },
  {
    teamId: "south_korea",
    records: [
      { opponent: "Bolivia", played: 3, won: 0, drawn: 2, lost: 1, goalsFor: 2, goalsAgainst: 4 },
      { opponent: "Argelia", played: 2, won: 1, drawn: 0, lost: 1, goalsFor: 4, goalsAgainst: 3 },
      { opponent: "Alemania", played: 2, won: 1, drawn: 0, lost: 1, goalsFor: 3, goalsAgainst: 4 },
      { opponent: "Portugal", played: 2, won: 1, drawn: 0, lost: 1, goalsFor: 3, goalsAgainst: 1 },
      { opponent: "México", played: 2, won: 0, drawn: 1, lost: 1, goalsFor: 2, goalsAgainst: 3 },
    ],
  },
  {
    teamId: "senegal",
    records: [
      { opponent: "Colombia", played: 2, won: 1, drawn: 0, lost: 1, goalsFor: 3, goalsAgainst: 2 },
      { opponent: "Ecuador", played: 1, won: 1, drawn: 0, lost: 0, goalsFor: 3, goalsAgainst: 0 },
      { opponent: "Países Bajos", played: 1, won: 0, drawn: 0, lost: 1, goalsFor: 0, goalsAgainst: 2 },
      { opponent: "Polonia", played: 1, won: 1, drawn: 0, lost: 0, goalsFor: 2, goalsAgainst: 1 },
      { opponent: "Inglaterra", played: 1, won: 0, drawn: 0, lost: 1, goalsFor: 0, goalsAgainst: 3 },
    ],
  },
  {
    teamId: "uruguay",
    records: [
      { opponent: "Bolivia", played: 4, won: 4, drawn: 0, lost: 0, goalsFor: 17, goalsAgainst: 2 },
      { opponent: "México", played: 3, won: 3, drawn: 0, lost: 0, goalsFor: 8, goalsAgainst: 1 },
      { opponent: "Brasil", played: 4, won: 2, drawn: 1, lost: 1, goalsFor: 6, goalsAgainst: 5 },
      { opponent: "Argentina", played: 4, won: 1, drawn: 1, lost: 2, goalsFor: 4, goalsAgainst: 6 },
      { opponent: "Alemania", played: 3, won: 1, drawn: 1, lost: 1, goalsFor: 4, goalsAgainst: 5 },
    ],
  },
];

export const worldCupEditions = [
  { year: 1930, host: "Uruguay", champion: "Uruguay", runnerUp: "Argentina" },
  { year: 1934, host: "Italia", champion: "Italia", runnerUp: "Checoslovaquia" },
  { year: 1938, host: "Francia", champion: "Italia", runnerUp: "Hungría" },
  { year: 1950, host: "Brasil", champion: "Uruguay", runnerUp: "Brasil" },
  { year: 1954, host: "Suiza", champion: "Alemania Occ.", runnerUp: "Hungría" },
  { year: 1958, host: "Suecia", champion: "Brasil", runnerUp: "Suecia" },
  { year: 1962, host: "Chile", champion: "Brasil", runnerUp: "Checoslovaquia" },
  { year: 1966, host: "Inglaterra", champion: "Inglaterra", runnerUp: "Alemania Occ." },
  { year: 1970, host: "México", champion: "Brasil", runnerUp: "Italia" },
  { year: 1974, host: "Alemania Occ.", champion: "Alemania Occ.", runnerUp: "Países Bajos" },
  { year: 1978, host: "Argentina", champion: "Argentina", runnerUp: "Países Bajos" },
  { year: 1982, host: "España", champion: "Italia", runnerUp: "Alemania Occ." },
  { year: 1986, host: "México", champion: "Argentina", runnerUp: "Alemania Occ." },
  { year: 1990, host: "Italia", champion: "Alemania Occ.", runnerUp: "Argentina" },
  { year: 1994, host: "Estados Unidos", champion: "Brasil", runnerUp: "Italia" },
  { year: 1998, host: "Francia", champion: "Francia", runnerUp: "Brasil" },
  { year: 2002, host: "Corea/Japón", champion: "Brasil", runnerUp: "Alemania" },
  { year: 2006, host: "Alemania", champion: "Italia", runnerUp: "Francia" },
  { year: 2010, host: "Sudáfrica", champion: "España", runnerUp: "Países Bajos" },
  { year: 2014, host: "Brasil", champion: "Alemania", runnerUp: "Argentina" },
  { year: 2018, host: "Rusia", champion: "Francia", runnerUp: "Croacia" },
  { year: 2022, host: "Qatar", champion: "Argentina", runnerUp: "Francia" },
  { year: 2026, host: "USA/México/Canadá", champion: "—", runnerUp: "—" },
];
