export interface TeamStats {
  id: string;
  name: string;
  flag: string;
  confederation: string;
  participations: number;
  bestPosition: string;
  played: number;
  won: number;
  drawn: number;
  lost: number;
  goalsFor: number;
  goalsAgainst: number;
  titles: number;
  finals: number;
  semifinals: number;
  firstYear: number;
  lastYear: number;
}

export interface H2HRecord {
  opponent: string;
  played: number;
  won: number;
  drawn: number;
  lost: number;
  goalsFor: number;
  goalsAgainst: number;
}

export interface TeamH2H {
  teamId: string;
  records: H2HRecord[];
}

export const worldCupTeams: TeamStats[] = [
  {
    id: "brazil",
    name: "Brasil",
    flag: "🇧🇷",
    confederation: "CONMEBOL",
    participations: 22,
    bestPosition: "Campeón",
    played: 114,
    won: 76,
    drawn: 19,
    lost: 19,
    goalsFor: 237,
    goalsAgainst: 101,
    titles: 5,
    finals: 7,
    semifinals: 11,
    firstYear: 1930,
    lastYear: 2022,
  },
  {
    id: "germany",
    name: "Alemania",
    flag: "🇩🇪",
    confederation: "UEFA",
    participations: 20,
    bestPosition: "Campeón",
    played: 109,
    won: 67,
    drawn: 20,
    lost: 22,
    goalsFor: 226,
    goalsAgainst: 125,
    titles: 4,
    finals: 8,
    semifinals: 13,
    firstYear: 1934,
    lastYear: 2022,
  },
  {
    id: "argentina",
    name: "Argentina",
    flag: "🇦🇷",
    confederation: "CONMEBOL",
    participations: 18,
    bestPosition: "Campeón",
    played: 88,
    won: 47,
    drawn: 16,
    lost: 25,
    goalsFor: 145,
    goalsAgainst: 97,
    titles: 3,
    finals: 5,
    semifinals: 6,
    firstYear: 1930,
    lastYear: 2022,
  },
  {
    id: "italy",
    name: "Italia",
    flag: "🇮🇹",
    confederation: "UEFA",
    participations: 18,
    bestPosition: "Campeón",
    played: 83,
    won: 45,
    drawn: 21,
    lost: 17,
    goalsFor: 128,
    goalsAgainst: 77,
    titles: 4,
    finals: 6,
    semifinals: 8,
    firstYear: 1934,
    lastYear: 2022,
  },
  {
    id: "france",
    name: "Francia",
    flag: "🇫🇷",
    confederation: "UEFA",
    participations: 16,
    bestPosition: "Campeón",
    played: 66,
    won: 38,
    drawn: 13,
    lost: 15,
    goalsFor: 120,
    goalsAgainst: 71,
    titles: 2,
    finals: 3,
    semifinals: 6,
    firstYear: 1930,
    lastYear: 2022,
  },
  {
    id: "england",
    name: "Inglaterra",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    confederation: "UEFA",
    participations: 16,
    bestPosition: "Campeón",
    played: 69,
    won: 32,
    drawn: 21,
    lost: 16,
    goalsFor: 91,
    goalsAgainst: 64,
    titles: 1,
    finals: 1,
    semifinals: 3,
    firstYear: 1950,
    lastYear: 2022,
  },
  {
    id: "spain",
    name: "España",
    flag: "🇪🇸",
    confederation: "UEFA",
    participations: 16,
    bestPosition: "Campeón",
    played: 67,
    won: 33,
    drawn: 15,
    lost: 19,
    goalsFor: 99,
    goalsAgainst: 77,
    titles: 1,
    finals: 1,
    semifinals: 2,
    firstYear: 1934,
    lastYear: 2022,
  },
  {
    id: "netherlands",
    name: "Países Bajos",
    flag: "🇳🇱",
    confederation: "UEFA",
    participations: 11,
    bestPosition: "Subcampeón",
    played: 52,
    won: 28,
    drawn: 10,
    lost: 14,
    goalsFor: 90,
    goalsAgainst: 60,
    titles: 0,
    finals: 3,
    semifinals: 4,
    firstYear: 1934,
    lastYear: 2022,
  },
  {
    id: "uruguay",
    name: "Uruguay",
    flag: "🇺🇾",
    confederation: "CONMEBOL",
    participations: 14,
    bestPosition: "Campeón",
    played: 56,
    won: 27,
    drawn: 10,
    lost: 19,
    goalsFor: 87,
    goalsAgainst: 74,
    titles: 2,
    finals: 2,
    semifinals: 5,
    firstYear: 1930,
    lastYear: 2022,
  },
  {
    id: "portugal",
    name: "Portugal",
    flag: "🇵🇹",
    confederation: "UEFA",
    participations: 9,
    bestPosition: "3° Puesto",
    played: 37,
    won: 20,
    drawn: 7,
    lost: 10,
    goalsFor: 71,
    goalsAgainst: 43,
    titles: 0,
    finals: 0,
    semifinals: 2,
    firstYear: 1966,
    lastYear: 2022,
  },
  {
    id: "croatia",
    name: "Croacia",
    flag: "🇭🇷",
    confederation: "UEFA",
    participations: 6,
    bestPosition: "Subcampeón",
    played: 26,
    won: 14,
    drawn: 4,
    lost: 8,
    goalsFor: 47,
    goalsAgainst: 32,
    titles: 0,
    finals: 1,
    semifinals: 2,
    firstYear: 1998,
    lastYear: 2022,
  },
  {
    id: "mexico",
    name: "México",
    flag: "🇲🇽",
    confederation: "CONCACAF",
    participations: 17,
    bestPosition: "Cuartos de Final",
    played: 57,
    won: 16,
    drawn: 14,
    lost: 27,
    goalsFor: 60,
    goalsAgainst: 99,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1930,
    lastYear: 2022,
  },
  {
    id: "morocco",
    name: "Marruecos",
    flag: "🇲🇦",
    confederation: "CAF",
    participations: 7,
    bestPosition: "4° Puesto",
    played: 22,
    won: 8,
    drawn: 4,
    lost: 10,
    goalsFor: 24,
    goalsAgainst: 29,
    titles: 0,
    finals: 0,
    semifinals: 1,
    firstYear: 1970,
    lastYear: 2022,
  },
  {
    id: "usa",
    name: "Estados Unidos",
    flag: "🇺🇸",
    confederation: "CONCACAF",
    participations: 11,
    bestPosition: "3° Puesto",
    played: 36,
    won: 12,
    drawn: 8,
    lost: 16,
    goalsFor: 43,
    goalsAgainst: 61,
    titles: 0,
    finals: 0,
    semifinals: 1,
    firstYear: 1930,
    lastYear: 2022,
  },
  {
    id: "japan",
    name: "Japón",
    flag: "🇯🇵",
    confederation: "AFC",
    participations: 7,
    bestPosition: "Cuartos de Final",
    played: 24,
    won: 9,
    drawn: 4,
    lost: 11,
    goalsFor: 28,
    goalsAgainst: 37,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 1998,
    lastYear: 2022,
  },
  {
    id: "senegal",
    name: "Senegal",
    flag: "🇸🇳",
    confederation: "CAF",
    participations: 3,
    bestPosition: "Cuartos de Final",
    played: 10,
    won: 4,
    drawn: 2,
    lost: 4,
    goalsFor: 11,
    goalsAgainst: 12,
    titles: 0,
    finals: 0,
    semifinals: 0,
    firstYear: 2002,
    lastYear: 2022,
  },
];

export const h2hData: TeamH2H[] = [
  {
    teamId: "brazil",
    records: [
      { opponent: "Argentina", played: 9, won: 4, drawn: 2, lost: 3, goalsFor: 14, goalsAgainst: 12 },
      { opponent: "Alemania", played: 8, won: 3, drawn: 1, lost: 4, goalsFor: 14, goalsAgainst: 18 },
      { opponent: "Italia", played: 4, won: 2, drawn: 1, lost: 1, goalsFor: 6, goalsAgainst: 5 },
      { opponent: "Francia", played: 4, won: 2, drawn: 0, lost: 2, goalsFor: 4, goalsAgainst: 5 },
      { opponent: "Inglaterra", played: 5, won: 4, drawn: 0, lost: 1, goalsFor: 8, goalsAgainst: 3 },
    ],
  },
  {
    teamId: "argentina",
    records: [
      { opponent: "Brasil", played: 9, won: 3, drawn: 2, lost: 4, goalsFor: 12, goalsAgainst: 14 },
      { opponent: "Alemania", played: 7, won: 2, drawn: 2, lost: 3, goalsFor: 10, goalsAgainst: 12 },
      { opponent: "Francia", played: 3, won: 2, drawn: 0, lost: 1, goalsFor: 8, goalsAgainst: 7 },
      { opponent: "Países Bajos", played: 6, won: 3, drawn: 2, lost: 1, goalsFor: 8, goalsAgainst: 6 },
      { opponent: "Italia", played: 2, won: 1, drawn: 0, lost: 1, goalsFor: 2, goalsAgainst: 2 },
    ],
  },
  {
    teamId: "germany",
    records: [
      { opponent: "Brasil", played: 8, won: 4, drawn: 1, lost: 3, goalsFor: 18, goalsAgainst: 14 },
      { opponent: "Argentina", played: 7, won: 3, drawn: 2, lost: 2, goalsFor: 12, goalsAgainst: 10 },
      { opponent: "Francia", played: 7, won: 4, drawn: 1, lost: 2, goalsFor: 15, goalsAgainst: 9 },
      { opponent: "Italia", played: 5, won: 2, drawn: 1, lost: 2, goalsFor: 8, goalsAgainst: 9 },
      { opponent: "Inglaterra", played: 5, won: 4, drawn: 0, lost: 1, goalsFor: 12, goalsAgainst: 5 },
    ],
  },
];

export const worldCupEditions = [
  { year: 1930, host: "Uruguay", champion: "Uruguay", runnerUp: "Argentina" },
  { year: 1934, host: "Italia", champion: "Italia", runnerUp: "Checoslovaquia" },
  { year: 1938, host: "Francia", champion: "Italia", runnerUp: "Hungría" },
  { year: 1950, host: "Brasil", champion: "Uruguay", runnerUp: "Brasil" },
  { year: 1954, host: "Suiza", champion: "Alemania Occ.", runnerUp: "Hungría" },
  { year: 1958, host: "Suecia", champion: "Brasil", runnerUp: "Suecia" },
  { year: 1962, host: "Chile", champion: "Brasil", runnerUp: "Checoslovaquia" },
  { year: 1966, host: "Inglaterra", champion: "Inglaterra", runnerUp: "Alemania Occ." },
  { year: 1970, host: "México", champion: "Brasil", runnerUp: "Italia" },
  { year: 1974, host: "Alemania Occ.", champion: "Alemania Occ.", runnerUp: "Países Bajos" },
  { year: 1978, host: "Argentina", champion: "Argentina", runnerUp: "Países Bajos" },
  { year: 1982, host: "España", champion: "Italia", runnerUp: "Alemania Occ." },
  { year: 1986, host: "México", champion: "Argentina", runnerUp: "Alemania Occ." },
  { year: 1990, host: "Italia", champion: "Alemania Occ.", runnerUp: "Argentina" },
  { year: 1994, host: "Estados Unidos", champion: "Brasil", runnerUp: "Italia" },
  { year: 1998, host: "Francia", champion: "Francia", runnerUp: "Brasil" },
  { year: 2002, host: "Corea/Japón", champion: "Brasil", runnerUp: "Alemania" },
  { year: 2006, host: "Alemania", champion: "Italia", runnerUp: "Francia" },
  { year: 2010, host: "Sudáfrica", champion: "España", runnerUp: "Países Bajos" },
  { year: 2014, host: "Brasil", champion: "Alemania", runnerUp: "Argentina" },
  { year: 2018, host: "Rusia", champion: "Francia", runnerUp: "Croacia" },
  { year: 2022, host: "Qatar", champion: "Argentina", runnerUp: "Francia" },
];
